#!/usr/bin/env bash
#
# This script indexes the solr.json which is generated by dumps data pipeline
# Whenever you need to index or re-index your data you can use this script.

echo "Indexing ontology collection in server localhost:8993"
curl --location --request POST 'http://localhost:8993/solr/ontology/update/json?commit=true' --header 'Content-Type: application/json' --data-binary '@solr.json'
