#!/usr/bin/env bash
#
# This script will be used at the end of pipeline deployment
# It indexes the solr.json which is generated by dumps data pipeline, configures
# the ontology schema by using solr_config.sh for partial search capability.
# Re-indexing is also takes place in order to generate newly added fields in the
# solr collection

while getopts h:p:c: flag
do
    case "${flag}" in
        h) host=${OPTARG};;
        p) port=${OPTARG};;
        c) collection=${OPTARG};;
        *) echo "!!! Invalid flag. Only -h and -p flags are supported."
    esac
done

bash ./solr_index.sh -h $host -p $port -c $collection

bash ./solr_config.sh -h $host -p $port -c $collection

bash ./solr_index.sh -h $host -p $port -c $collection
