#!/usr/bin/env bash
#
# This script indexes the solr.json generated by the dumps data pipeline.
# Use it to index or re-index your data.

usage() {
  echo "Usage: $0 -h <host> -p <port> -c <collection>"
  exit 1
}

# Parse command-line options
while getopts "h:p:c:" flag; do
  case "${flag}" in
    h) host=${OPTARG} ;;
    p) port=${OPTARG} ;;
    c) collection=${OPTARG} ;;
    *) usage ;;
  esac
done

# Verify required options are set
if [[ -z "$host" || -z "$port" || -z "$collection" ]]; then
  echo "Error: host, port, and collection must all be specified."
  usage
fi

BASE_URL="http://${host}:${port}/solr"

echo "Deleting all documents from Solr collection '${collection}'..."
curl -s -X POST -H "Content-Type: application/json" "${BASE_URL}/${collection}/update?commit=true" \
     -d '{ "delete": {"query":"*:*"} }'

echo "Indexing '${collection}' from solr.json into ${host}:${port}..."
curl -s --location --request POST "${BASE_URL}/${collection}/update/json?commit=true" \
     --header "Content-Type: application/json" --data-binary "@solr.json"

echo "Done."
