PREFIX efo: <http://www.ebi.ac.uk/efo/>

CONSTRUCT {
	?s <http://n2o.neo/property/nodeLabel> "Assay" .
}
WHERE {
VALUES ?s
{efo:EFO_0009901 #10x 3' v1
efo:EFO_0009899 #10x 3' v2
efo:EFO_0009922 #10x 3' v3
efo:EFO_0011025 #10x 5' v1
efo:EFO_0030059 #10x multiome
efo:EFO_0700006 #ExSeq
efo:EFO_0030060 #mCT-seq
efo:EFO_0008992 #MERFISH
efo:EFO_0008853 #Patch-seq
efo:EFO_0008919 #Seq-Well
efo:EFO_0030019 #Seq-Well S3
efo:EFO_0008930 #Smart-seq
efo:EFO_0008931 #Smart-seq2
efo:EFO_0700007 #targeted ExSeq
efo:EFO_0700008 #untargeted ExSeq
efo:EFO_0010961 #Visium Spatial Gene Expression
  }
}
