PREFIX : <http://virtualflybrain.org#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {
	?x ?p ?y .
}

WHERE {
	?x ?p ?y .
	FILTER(isIRI(?x))
	FILTER(isIRI(?p))
	FILTER(isIRI(?y))
}

LIMIT 10000