PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {
	?x <http://n2o.neo/property/nodeLabel> "has_region_connectivity" .
}
WHERE {
  ?x <http://purl.obolibrary.org/obo/RO_0002113>|<http://purl.obolibrary.org/obo/RO_0002110> ?y . 
  ?x rdf:type owl:NamedIndividual .
}
