PREFIX : <http://purl.obolibrary.org/obo/PCL_>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

CONSTRUCT {
	:Ontology rdf:type owl:Class .
  :Ontology rdfs:label ?title .
  :Ontology dc:title ?title .
#  :Ontology dc:description ?desc .
  :Ontology owl:versionInfo ?versionInfo .
}
WHERE {
  ?ontology rdf:type owl:Ontology .
  ?ontology dc:title ?title .
#  ?ontology dc:description ?desc .
  ?ontology owl:versionInfo ?versionInfo .
}
