# Add species semantic tags species to assist with contextual filtering for developmental stage terms

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
   ?s <http://n2o.neo/property/nodeLabel> "Mus_musculus" .
 }
WHERE {
  ?s rdfs:label ?o
  FILTER(STRSTARTS(str(?s), "http://purl.obolibrary.org/obo/MmusDv_"))
}